### ISSUE TITLE
@conda-forge-admin, please add user @dopplershift

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/myst-parser-feedstock#37]
My packages are dependent on this for building docs (and passing CI) so I'm happy to help keep this up to date.

**Comment by chrisjsewell** [comment]
It can't be updated until https://github.com/conda-forge/staged-recipes/pull/17149 is merged

**Comment by chrisjsewell** [comment]
cheers!

@choldgraf you need to do this, https://github.com/conda-forge/markdown-it-py-feedstock/pull/22 and https://github.com/conda-forge/myst-parser-feedstock/pull/36

**Comment by choldgraf** [comment]
@dopplershift are you willing to help with https://github.com/conda-forge/markdown-it-py-feedstock/pull/22 as well? I don't have time to maintain that feedstock but happy to add maintainer rights. I might need guidance on how to do this because i know nothing about conda forge

**Comment by dopplershift** [comment]
Sure, I can help keep the conda-forge package up to date.

**Comment by choldgraf** [comment]
@dopplershift I've added you on both 👍 many thanks 🙏
